.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
CHANGELOG.md
README.md
landingzones/landingzone_caf_foundations/blueprint_foundations_accounting/main.tf
landingzones/landingzone_caf_foundations/blueprint_foundations_governance/main.tf
landingzones/landingzone_caf_foundations/blueprint_foundations_security/main.tf
landingzones/landingzone_caf_foundations/main.tf
landingzones/landingzone_vdc_demo/blueprint_networking_shared_egress/main.tf
landingzones/landingzone_vdc_demo/blueprint_networking_shared_services.sandpit.auto.tfvars
landingzones/landingzone_vdc_demo/blueprint_networking_shared_services/main.tf
landingzones/landingzone_vdc_demo/blueprint_networking_shared_transit/main.tf
landingzones/landingzone_vdc_demo/main.tf

Update for the 2002.0320 rover runtime

---

landingzones/landingzone_caf_foundations/readme.md

Following 'getting started' walk-throughs of the rover, I deployed the foundational landing zone. Naturally, I'll like to see what it does. Following the source, I arrive at this part of the repository, but that's where the trail ends for me.
Having a link to the CAF documentation will allow readers that are 'looking through the stack' to learn about the Terraform approach to CAF a follow on trail to get more understanding on what they are getting into, albeit a bottom-up trail back to those high-level docs.

Added reference to CAF docs, for longer details

---

landingzones/landingzone_networking/firewall.tf
landingzones/landingzone_networking/vnet.tf

Breaking change - require to teardown the caf foundations and re-deploy.
Configuration files of caf-fondations must be updated to support the multi-region

Add multi-region diagnostic support

---

landingzones/landingzone_caf_foundations/blueprint_foundations_governance/policies/builtin/allowed_resource_type.tf

Added the missing encoding.
With the fix, the plan will succeed and allow apply:
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
```
+ resource "azurerm_policy_assignment" "res_type" {
+ description          = "Policy Assignment with Terraform"
+ display_name         = "TF Restrict Deployment of specified Azure Resources"
+ enforcement_mode     = true
+ id                   = (known after apply)
+ name                 = "res_svc"
+ parameters           = jsonencode(
{
+ listOfResourceTypesAllowed = {
+ value = [
+ "Microsoft.Network/publicIPAddresses",
+ "Microsoft.Compute/disks",
]
}
}
)
+ policy_definition_id = …
```

[bugfix] Fixed passing in the list of supported services

---

landingzones/caf_launchpad/add-ons/terraform_cloud/example/tfc.tfvars
landingzones/caf_launchpad/add-ons/terraform_cloud/main.tf
landingzones/caf_launchpad/add-ons/terraform_cloud/readme.md
landingzones/caf_launchpad/add-ons/terraform_cloud/terraform_cloud.tf
landingzones/caf_launchpad/add-ons/terraform_cloud/variables.tf

Supported scenario in this release:
Future scenarios:

Initial support for TFC bootstrap as add-on

---

documentation/getting_started/getting_started.md

The command doesn't work, the output is:
You need to deploy the launchpad from the rover by running:
rover -lz /tf/caf/landingzones/launchpad -a apply -launchpad -env sandpit
I've taken the command from https://github.com/Azure/caf-terraform-landingzones/tree/master/landingzones/caf_launchpad
---

Change Launchpad creation command

---

landingzones/caf_solutions/locals.remote_tfstates.tf
landingzones/caf_solutions/output.tf

---
Adding resource_groups and virtual_machines in the output to be reused from other LZ

add RG and VM in output

---

caf_solution/add-ons/databricks/variables.tf
caf_solution/local.networking.tf
caf_solution/local.remote.tf
caf_solution/variables.networking.tf

add waf policy

---

caf_solution/vm_extensions.tf

add vm_extension.tf to caf_solution

---

caf_solution/landingzone.tf
caf_solution/local.cloud.tf
caf_solution/variables.cloud.tf

---
- [ NA] I have updated the documentation accordingly.
- [ NA] I have added tests to cover my changes.
- [Pending] All new and existing tests passed.
- [x ] My code follows the code style of this project.
This PR resolves part one of the bug issue. See issue for other parts.
Added complex cloud variable to store endpoints and suffixes from the logged in cloud
- Retrieve az cloud show endpoints and suffixes 
- Convert to variables to be passed to the modules
- Added Azure Public Cloud default values in the case the code is run without Rover
- Can change to null defaults but opted for greater modularity.
closes #183 
Use Azure update, Login to AzureUSGovernment and deploy a MSSQL db with db_permissions to see appropriate cloud URI in use.

Add sovereign cloud endpoints and suffix environment variables (part 2)

---

caf_solution/add-ons/aks_applications/locals.remote_tfstates.tf

---
This change updates the aks_applications add-on in caf_solution to pull aks cluster information using the new caf_solution object model.
Create a demo or sandpit environment from the starter repo. After deploying aks on level3, deploy argo cd on level4 and it should correctly deploy the argo helm chart.

update aks add-on for aks cluster remote object

---

caf_solution/landingzone.tf
caf_solution/local.remote.tf

Reverts Azure/caf-terraform-landingzones#188

Revert "Add vhub route tables as a remote object"

---

caf_solution/landingzone.tf
caf_solution/variables.tf

---
Add support for Terraform Random String resource so that the user can user the random strings for passwords and others purposes
Related PR in terraform-azurerm-caf
https://github.com/aztfmod/terraform-azurerm-caf/pull/508
random_strings = {
jwt = {
length = 25
}
}

Add Random_String Implementation

---

caf_solution/local.storage.tf
caf_solution/variables.storage.tf

---
- [ x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
This PR adds a variable and output for Azure Storage Queues so that we may capture any relevant outputs that need to be used downstream, for example, the queue name and location.

add variable object for storage account queues

---

caf_solution/add-ons/aks-secure-baseline/kustomization.yaml

A reference to the [caf-terraform-starter](https://github.com/Azure/caf-terraform-landingzones-starter/) project had to be updated. The [file in question](https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/flux/flux.yaml) had moved due to a change in the folder structure.
---
The path to `flux.yaml` is outdated now that the caf-terraform-starter project has had some new changes to folder structure. Thus, this change will refer to the file in its new location.
1. Open up Kustomization.yaml on your IDE.
2. Open the link in line 5 and ensure it points to a valid URL.

Update path to flux.yaml in kustomization.yaml

---

caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf

Fix subnet_keys role assignment for aks_secure_baseline_v2

---

caf_solution/add-ons/aks-secure-baseline/aks-pod-identity-assignment.tf
caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf

aks-secure-baseline add-on doesn't work when using an user-assigned identity (user-msi)
**To Reproduce**
Steps to reproduce the behavior:
1. Create an AKS Cluster using UserAssigned identity
2. Apply the aks-secure-baseline (v1 or v2) add-on on the configuration
3. See error in the below screenshot 
**Expected behavior**
The principal id value cannot be null when you do a role assignment. This value needs to be fetched from managed identity  and used while doing the role assignment using the user msi.
**Screenshots**
Testing done with an aks cluster created with user assigned identity. Sample tfvars snippet below:
```
aks_clusters = {
cluster_dev_temp = {
lz_key = "lz_key_for_aks"
key = "cluster_key"
identity = {
type = "UserAssigned"
managed_identity_key = "msi_key"
lz_key = …
```

Update aks-secure-baseline add-ons (V1 and V2) to support aks cluster with user assigned identity

---

caf_solution/locals.remote_tfstates.tf

Update to support default global settings key

---

caf_solution/add-ons/cross_tenant_hub_connection/providers.tf

The add-on can be used to connect a vnet and a vhub in different subscriptions / same tenant or different tenant.
This change adds the support for the same tenant when using azure AD service principals.
```hcl
virtual_hub_subscription_id = "xxxx"
virtual_hub_tenant_id       = "yyyy"
virtual_hub_lz_key          = "connectivity_virtual_hub1"
virtual_network_subscription_id = "uuuuu"
virtual_network_tenant_id       = "vvvv"
virtual_hub_connections = {
project2_to_hub1 = {
name = "project2-to-hub1"
virtual_hub = {
lz_key = "connectivity_virtual_hub1"
key    = "hub1"
}
vnet = {
lz_key   = "project2-resources"
vnet_key = "project2"
}
}
}
```

Auxiliary tenant is optional when peering in the same tenant

---

caf_solution/scenario/networking/106-hub-virtual-wan-firewall/peerings.tfvars
caf_solution/scenario/networking/106-hub-virtual-wan-firewall/virtual_hubs.tfvars
caf_solution/scenario/networking/106-hub-virtual-wan-firewall/virtual_wan.tfvars

Multiple issues in CI/CD for 106 deployment example. 
Updating to latest structures to fix RG and vwan structure.
---

Update example 106 - virtual wan structure

---

caf_solution/local.remote.tf

ACR entries are stored as `azure_container_registries` in the state file. This PR corrects the attribute name so that an ACR declared in a remote lz can be used.
e.g.
```
{
"outputs":{
"objects":{
"value":{
"lz_key":{
"azure_container_registries":{
"acr1":{ ... }
}
}
}
}
}
}
```
---
Try referencing an ACR declared in a remote lz, e.g. for role mapping
```
role_mapping = {
built_in_role_mapping = {
azure_container_registries = {
acr1 = {
lz_key = "remote_lz"
"AcrPull" = {
aks_clusters = {
keys = ["cluster_re1"]
}
}
}
}
}
}
```

Use correct attribute name for ACR

---

caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/projects.tfvars
caf_solution/add-ons/azure_devops_v1/variables.tf

organization_url doesn't appear to be used anywhere - remove from
examples and module to avoid confusion.
```bash
$ grep -ri organization_url caf-terraform-landingzones caf-terraform-landingzones-starter
caf-terraform-landingzones/caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/projects.tfvars:organization_url = "https://dev.azure.com/azure-terraform"
caf-terraform-landingzones/caf_solution/add-ons/azure_devops_v1/variables.tf:variable "organization_url" {
```

Remove unused var from azure_devops_v1

---

caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.tf

For reasons that are not entirely clear to me yet, CAF Terraform
has two ways of creating service principals:
```
aad_apps {
}
```
or,
```
azuread_applications {
}
```
Also for reasons not yet clear to me, this repo provides two lzs for
configuring AZDO: caf_solution/add-ons/azure_devops and
caf_solution/add-ons/azure_devops_v1
The azure_devops module appears to use aad_apps, while azure_devops_v1
uses azuread_applications. This commit updates azure_devops_v1 to
support both forms of AD config.

Support aad_apps for AZDO service endpoints

---

caf_solution/landingzone.tf
caf_solution/local.networking.tf
caf_solution/local.remote.tf
caf_solution/variables.networking.tf

Add support for application_gateway_applications_v1

---

caf_solution/add-ons/azure_devops_agent/local.azuread.tf
caf_solution/add-ons/azure_devops_agent/solution.tf
caf_solution/add-ons/azure_devops_agent/variables.tf

To resolve error below"
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
hashicorp/azurerm: no available releases match the given constraints ~>
2.55.0, ~> 2.81.0
---

update version and remove unused var

---

caf_solution/local.database.tf
caf_solution/local.remote.tf
caf_solution/variables.database.tf

Changes to enable a CosmosDB SQL Database to be defined independently of a CosmosDB Account. Allows you to create a shared account in one LZ and add project-specific databases in different LZs. 
Requires https://github.com/aztfmod/terraform-azurerm-caf/pull/725
---
Create a cosmosdb account in one lz and the cosmosdb_sql_account in another, e.g.
Level 3 - application infrastructure lz
```
landingzone = {
backend_type        = "azurerm"
global_settings_key = "connectivity"
level               = "level3"
key                 = "application_infra"
tfstates = {
connectivity = {
level   = "lower"
tfstate = "connectivity.tfstate"
}
}
}
resource_groups = {
cosmos_re1 = {
name   = "rg-cosmos-shared"
region = "region1"
}
}
cosmos_dbs = {
cosmosdb_account_shared = {
name                      = …
```

Add support for cosmosdb_sql_databases

---

caf_solution/add-ons/aad-pod-identity/variables.tf

aks_cluster_vnet_key isn't used anywhere in this addon, but there's no
default so terraform will make you supply one. Remove it.
---

Remove unused var from add-ons/aad-pod-identity

---

caf_solution/add-ons/secrets-store-csi-driver-provider-azure/README.md
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/backend.azurerm
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/kustomization_build.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/main.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/variables.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/csi_keyvault_provider.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/local.remote_tfstates.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/main.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/output.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/providers.tf
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/secretproviderclass.yaml
caf_solution/add-ons/secrets-store-csi-driver-provider-azure/variables.tf

This copies the pattern used in `add-ons/aad-pod-identity` to create and
apply a `SecretProviderClass` in AKS.
This is required to sync and mount secrets from KeyVault into pods using
the `secrets-store-csi-driver-provider-azure` AKS addon.
---

Add module for configuring SecretClass for CSI

---

caf_solution/add-ons/aad-pod-identity/aad-msi-binding.yaml
caf_solution/add-ons/aad-pod-identity/aad_pod_identity.tf

Currently the name of the `AzureIdentity` / `AzureIdentityBinding` objects
created as part of the `aad-pod-identity` lz addon have hardcoded names.
This made it not possible to create more than one pair for one MSI.
This patch applies `kustomise` to each field allowing for more
customisation.
It also adds a new 'selector' argument in the case the user doesn't want
the name of the MSI used in this field:
```
managed_identities = {
ingress_msi = {
lz_key = "aks"
aadpodidentity_selector = "ingress"
msi_keys = [
"ingress",
]
}
}
```
If `aadpodidentity_selector` is not specified the MSI name is used as
before.
---

Allow full kustomisation of aad-msi-binding.yaml

---

caf_solution/add-ons/azure_devops/main.tf
caf_solution/add-ons/azure_devops_agent/main.tf

https://github.com/Azure/caf-terraform-landingzones/commit/45b14a4d7b3326e5351dc7b7a18a8035b9882c04 introduced in issue in the azure_devops and azure_devops_agent add-ons which leads to conflict in azurerm provider requirements:
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: no available releases match the given constraints ~> 2.55.0, ~> 2.81.0
Both add-ons are still pinned to version 5.3.0 of the aztfmod/caf/azurerm module. This itself has a requirement on 2.55.0 of the azurerm provider, thus the conflict.

remove azurerm provider requirements

---

caf_solution/local.shared_services.tf
caf_solution/variables.shared_services.tf

---
Adds support for the [azurerm_monitor_autoscale_setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting) resource.
Related to [PR 803](https://github.com/aztfmod/terraform-azurerm-caf/pull/803) from the [terraform-azurerm-caf](https://github.com/aztfmod/terraform-azurerm-caf) repository.

Add monitor_autoscale_setting(s) module

---

caf_solution/add-ons/azure_devops_v1/azdo_pipelines.tf
caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.github.tf
caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.tf
caf_solution/add-ons/azure_devops_v1/readme.md

In order to source pipeline yamls from Github (non public repos), we
need to create a service connection.
This commit updates the service endpoint functionality to understand a
'type' value. For the existing configs, default type to 'TfsGit' if none
is specified. If type is set to 'Github', then use the new logic under
azdo_service_endpoint.github.tf to provision the connection.
The various values for 'type' are shown at https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/build_definition#repo_type - however this commit only implements Github.
A similar pattern should be possible to implement Bitbucket / GitHubEnterprise.
NOTE: similar to azdo-pat-admin, a Github PAT must be manually created
and stored in the keyvault identified in the 'keyvault {}' block: …

Add support for Github service connections

---

caf_solution/add-ons/cross_tenant_hub_connection/hub_connection.tf

[Add-on cross_tenant_hub_connection does not work with virtual hub that is part of a virtual wan #294](https://github.com/Azure/caf-terraform-landingzones/issues/294)
---
Add ability to specify vwan_key for virtual hubs that are a part of a virtual wan in the add-on cross_tenant_hub_connection

Add ability to specify vwan_key for virtual hubs that are part of a virtual WAN

---

caf_solution/add-ons/azure_devops_v1/azdo_service_endpoints.acr.tf
caf_solution/add-ons/azure_devops_v1/locals.remote_tfstates.tf

Introduces a new component `service_endpoints_acr` to add a Docker Registry service connection to Azure DevOps from an Azure Container registry created in a previous landing zone.
It uses the `azuredevops_serviceendpoint_dockerregistry` resource rather than the `azuredevops_serviceendpoint_azurecr` resource, as the latter requires to be able to create a service principal for connecting to the ACR on demand, which seems not feasible to me.
The component requires an existing `azure_container_registries` with `admin_enabled`.

add-ons/azure_devops_v1: add service endpoints for Azure container registry

---

caf_solution/add-ons/azure_devops_v1/azdo_pipelines.tf
caf_solution/add-ons/azure_devops_v1/azuredevops_group_membership/group_membership.tf
caf_solution/add-ons/azure_devops_v1/azuredevops_group_membership/main.tf
caf_solution/add-ons/azure_devops_v1/azuredevops_group_membership/variables.tf
caf_solution/add-ons/azure_devops_v1/azuredevops_projects.tf
caf_solution/add-ons/azure_devops_v1/variables.tf

This commit extends `azure_devops_v1` to allow the user to create groups,
and assign these groups permissions to AZDO projects and pipelines
("build definitions").
The following example will:
1. Create a group in AZDO called "Contoso Group"
2. Added UPNs paul and john to this group
3. Assign this group full permissions on the project and builds.
```
groups = {
contoso = {
project_key  = "contoso_project"
display_name = "Contoso Group"
description  = "Group for Contoso Team Members"
members = {
user_principal_names = [
"paul.bourke@contoso.com",
"john.doe@contoso.com",
]
}
}
}
permissions = {
projects = {
contoso_project = {
group_key = "contoso_project"
permissions = {
"GENERIC_READ"     = "Allow",
"GENERIC_WRITE"    = "Allow",
"START_BUILD"      = "Allow",
"ADMINISTER_BUILD" = "Allow",
} …
```

Add groups and permissions for azure_devops_v1

---

templates/platform/level2/asvm/ansible.yaml

Aci network

---

templates/enterprise-scale/contoso/asvm/orion-landingzone/deployments/orion_dev.yaml
templates/enterprise-scale/contoso/asvm/orion-landingzone/deployments/orion_prod.yaml
templates/enterprise-scale/contoso/asvm/orion-landingzone/deployments/subscriptions.yaml
templates/enterprise-scale/contoso/asvm/orion-landingzone/readme.md
templates/enterprise-scale/contoso/platform/single_subscription/credentials.yaml
templates/platform/level2/asvm/keyvaults.tfvars.j2
templates/platform/level3/ansible.yaml
templates/platform/level3/readme.md
templates/platform/level3/subscriptions/readme.md
templates/resources/keyvaults.tfvars.j2
templates/resources/landingzone.tfvars.j2

Udpate orion

---

caf_solution/add-ons/azure_devops_agent/scenario/200-contoso_demo/level0/virtual_machines.tfvars
caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf

Added option for ADO agent to use full storage blob urls that are created outsiide of the same LZ

---

caf_solution/local.shared_services.tf
caf_solution/variables.shared_services.tf

---
Tried provisioning the resource `azurerm_log_analytics_storage_insights` but variables were undeclared. Related to https://github.com/aztfmod/terraform-azurerm-caf/pull/1025

Add log analytics storage insights

---

templates/asvm/orion/resources.asvm.yaml

#346 
---
- can't test because my setup uses different keys. Logic works with my keys in my setup.
March platform release deploys two firewalls:
Hub attached firewall connectivity_secure_firewalls_env
VNet attached firewall as a central DNS instance connectivity_private_dns_firewalls_env
This change adds to correct firewall as dns server of the newly created VNet.
See the linked issue
It will change the current DNS Setting of existing ASVM Subscriptions. In my opinion, this setting is correct.
Build a level0 to level3 landingzone based on the march release, then use the asvm to create a hub attached subscription.
In my modified scenario, my change worked fine.

fixing dns server reference

---

caf_solution/local.networking.tf
caf_solution/local.remote.tf
caf_solution/variables.networking.tf

---
Created Super Module logic for resource public ip prefix. Public IP prefix can be refrenced from public ip resouce and remote states. Depends on https://github.com/aztfmod/terraform-azurerm-caf/pull/1049
Need some guiding in how to develop the automated test, but we have run manually tests from local VS. Is it Main branch or aci_network how is the primary branch for this repository?

blinQ - Add resource type public ip prefix

---

caf_solution/add-ons/aks_applications/app/module.tf
caf_solution/add-ons/aks_applications/app/variables.tf
caf_solution/add-ons/aks_applications/applications.tf
caf_solution/add-ons/aks_applications/locals.remote_tfstates.tf
caf_solution/add-ons/aks_applications/main.tf

This patch allows the use of ACR as a repository for helm charts.
Example usage:
```
helm_charts = {
mychart = {
name       = "mychart"
chart      = "mychart"
namespace  = "default"
version    = "0.0.1"
azure_container_registry = {
lz_key   = "devops"
key      = "devops_acr"
username = "00000000-0000-0000-0000-000000000000"
}
}
}
```
Note, the version bump of the helm provider is for the recently added
oci support: https://github.com/hashicorp/terraform-provider-helm/issues/666
---

Add auth for ACR to aks_applications

---

templates/resources/data_factory.tfvars.j2

---
Adds j2 template support for the Azure Data Factory (data_factory) resource type.
- [ X ] NO
data_factory:
df1:
name: df1{{landingzone_definition}}{{env}}
resource_group_key: integration
managed_virtual_network_enabled: true
private_endpoints:
df1-factory:
name: adf-int-acct
resource_group_key: integration
vnet_key: vnet
subnet_key: private_endpoints
identity:
type: SystemAssigned
identity_ids: None
private_service_connection:
name: adf-int-psc
is_manual_connection: false
subresource_names:
- dataFactory
private_dns:
zone_group_name: privatelink.datafactory.azure.net
zone_keys:
- privatelink.datafactory.azure.net
lz_key: …

Adds data factory j2 resource template

---

caf_launchpad/main.tf
caf_launchpad/variables.tf

---
Add support for configuring `purge_soft_delete_on_destroy` for launchpad keyvaults. 
If you have `purge_protection_enabled = true` on any of your launchpad keyvaults then the launchpad should not attempt to purge keyvaults/keyvault objects when they are deleted. This PR adds support for that.
Bootstrap a launchpad with a keyvault configuration containing `purge_soft_delete_on_destroy`, e.g.
```
keyvaults = {
level0 = {
name                     = "kv-mycompany-level0-shared"
resource_group_key       = "level0"
sku_name                 = "standard"
soft_delete_enabled      = true
purge_protection_enabled = true
tags = {
tfstate = "level0"
}
diagnostic_profiles = {
operations = {
definition_key   = "default_all"
destination_type = "log_analytics"
destination_key  = "central_logs"
}
siem …
```

Add support for configuring launchpad purge_soft_delete_on_destroy on Launchpad Key Vaults

---

templates/resources/azure_container_registries.tfvars.j2

---
Adds j2 resource template for azure container registry resource type
- [ X ] NO
azure_container_registries:
acr1:
name: {{landingzone_definition}}{{env}}acr001
resource_group_key: consumption
sku: Premium
admin_enabled: true
georeplications:
region2:
tags:
region: centralus

Adds azure container registry j2 resource template

---

templates/resources/bastion_hosts.tfvars.j2

---
Adds j2 template for the bastion_hosts resource type
- [ X ] NO
bastion_hosts:
bastion_hub:
name: {{landingzone_definition}}{{env}}bastion001
region: region1
resource_group_key: sharedservices
vnet_key: vnet
subnet_key: bastion
public_ip_key: bastion_host

Adds bastion_hosts j2 resource template

---

caf_solution/local.custom_variables.tf
caf_solution/main.tf
templates/platform/level1/alz/ansible.yaml
templates/platform/level1/alz/lib/v1.1.3/archetype_config_overrides.tfvars.j2
templates/platform/level1/alz/lib/v1.1.3/custom_landing_zones.tfvars.j2
templates/platform/level1/alz/subscription_id_overrides.tfvars.j2

---
Previoulsy to connect a vnet to a vhub in a different subscription, you had to set the global_settings_key to the virtual hub tfstate. With this update you can set the subscription id and tenant id (optional) of the vhub. Terraform will use those values to configure the azurerm.vhub provider alias.
```
custom_variables = {
virtual_hub_subscription_id = "xxxxxx"
}
```

Set subscription id and tenant id in custom_variables

---

caf_solution/local.database.tf
caf_solution/variables.database.tf

This allows use of the new related functionality in
terraform-azurerm-caf, which allows for adding entries to an azure
appconfig instance in a more flexible way.
See, https://github.com/aztfmod/terraform-azurerm-caf/pull/1221
---

Add new var: app_config_entries

---

caf_solution/local.remote.tf

---
Currently, there is no option of referencing remote virtual subnets in the context where existing non-CAF virtual networks are provisioned by external vendors due to organisational requirements. As such, there is a constraint referencing a remote virtual network via attribute `vnet_key`. There is a need to reference `subnet_key` directly.
The PR allows for pulling a remote terraform state where the virtual subnets have been created prior, for referencing in current landing zones.

Add remote virtual subnets referencing

---

caf_solution/local.shared_services.tf
caf_solution/variables.shared_services.tf

At the moment, we can't create monitor_metric_alert using [caf-terraform-landingzones](https://github.com/Azure/caf-terraform-landingzones). It is simply missing the variable. Could we please merge this simple PR?
Thank you very much
The root module does not declare a variable named "monitor_metric_alert" but
a value was found in file
"/__w/7/s/configuration/monitor_action_groups.tfvars".

Support monitor_metric_alert

---

caf_solution/local.shared_services.tf
caf_solution/variables.shared_services.tf

---
monitor_activity_log_alert variable has to be passed to aztfmod module for it to work.
This simple PR fix the issue
@microsoft-github-policy-service agree

Adding monitor_activity_log_alert

---

caf_solution/add-ons/caf_eslz/enterprise_scale.tf
caf_solution/add-ons/caf_eslz/main.tf
caf_solution/add-ons/caf_eslz/variables_alz.tf

Added subscription_id_identity to ES for custom landing zone support

Added subscription_id_identity

---

caf_solution/main.tf

Adding Feature block on Azure Keyvault as its required for azurerm version 2.99.0
---
- [ X ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.
- [ X ] I ran lint checks locally prior to submission.
- [ X ] NO
provider_azurerm_features_keyvault= {
recover_soft_deleted_key_vaults = true
}

Enabling feature block for purge_soft_delete_on_destroy, recover_soft_deleted_key_vaults

---

caf_solution/landingzone.tf

---
- [x ] I have added tests to cover my changes.
The landingzone.tf file in caf_solution is incorrectly using var.logic_app when it should be using local.logic_app , and this causes only resource groups to be created when following https://github.com/aztfmod/terraform-azurerm-caf/blob/int-5.7.0/examples/logic_app/104-logic_app_action_custom/configuration.tfvars example
- [x ] NO

Update landingzone.tf - changed var.logic_app to local.logic_app

---

caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
caf_solution/add-ons/caf_eslz/enterprise_scale.tf
caf_solution/add-ons/caf_eslz/main.tf
caf_solution/add-ons/caf_eslz/variables.tf

Update add-on eslz to 4.2.0, tested with my dev tenant and lz configuration. Fix minor issues with sourcing subscription_id and alligned hashicorp/azurerm provider version with caf_colution (3.54)
---

Update eslz to 4.2.0 and fix minor issues

---

caf_solution/local.remote.tf

Added lb_backend_address_pool to local.remote.tf to make possible to create a network_interface_backend_address_pool_association from another LZ.
Create a Load Balancer with backendpools and then in another LZ create a network_interface_backend_address_pool_association and refer with a lz_key to the backendpools.
Without this change it was not possible to refer from another LZ to the LB backendpool.

Add lb_backend_address_pool to remote
