landingzone_caf_foundations/blueprint_foundations.sandpit.auto.tfvars, landingzone_caf_foundations/blueprint_foundations/blueprint.tf, landingzone_caf_foundations/blueprint_foundations/main.tf, landingzone_caf_foundations/blueprint_foundations/output.tf, landingzone_caf_foundations/blueprint_foundations/variable.tf, landingzone_caf_foundations/foundations.tf, landingzone_caf_foundations/output.tf, landingzone_caf_foundations/variables_foundations.tf
Includes:
- Security Center Switch
- Refactoring to ease future multi region
=> November refresh

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, workspace.code-workspace
Adding support for VSCode dev containers.
=> Initial commit to support VSCode dev containers

landingzone_vdc_demo/blueprint_networking_shared_egress.sandpit.auto.tfvars, landingzone_vdc_demo/blueprint_networking_shared_egress/blueprint.tf, landingzone_vdc_demo/blueprint_networking_shared_services/blueprint.tf, landingzone_vdc_demo/blueprint_networking_shared_services/output.tf, landingzone_vdc_demo/blueprint_networking_shared_transit.sandpit.auto.tfvars, landingzone_vdc_demo/blueprint_networking_shared_transit/blueprint.tf, landingzone_vdc_demo/blueprint_operations/blueprint.tf, landingzone_vdc_demo/blueprint_tranquility/blueprint.tf, landingzone_vdc_demo/blueprint_tranquility/output.tf, landingzone_vdc_demo/blueprint_tranquility/variable.tf, landingzone_vdc_demo/networking_shared_egress.tf, landingzone_vdc_demo/networking_shared_services.tf, landingzone_vdc_demo/networking_shared_transit.tf, landingzone_vdc_demo/operations.tf, landingzone_vdc_demo/tranquility.tf
- Move region management into the landing zone
- Cleanup config files
=> November review

README.md
The link is redirected wrongly due to syntax issue.
- Updated the `https://aka.ms/caf` URL link to markdown syntax.
=> Updated the URL link in README.md

.github/workflows/ci-branches-vnext13.yml, environments/integration-tests/landingzone_caf_foundations/landingzone_caf_foundations_southeastasia_random.tfvars, landingzones/landingzone_caf_foundations/foundations.sandpit.auto.tfvars, landingzones/landingzone_networking/README.md, landingzones/landingzone_networking/backend.azurerm, landingzones/landingzone_networking/bastion.tf, landingzones/landingzone_networking/ddos.tf, landingzones/landingzone_networking/examples/102-multiple-vnets-peering/configuration.tfvars, landingzones/landingzone_networking/examples/103-hub-vnet-with-firewall/configuration.tfvars, landingzones/landingzone_networking/examples/104-hub-vnet-with-firewall-bastion/configuration.tfvars, landingzones/landingzone_networking/examples/105-hub-virtual-wan-firewall/configuration.tfvars, landingzones/landingzone_networking/firewall.tf, landingzones/landingzone_networking/main.tf, landingzones/landingzone_networking/modules/firewall_rules/application_rule_collection.tf, landingzones/landingzone_networking/modules/firewall_rules/nat_rule_collection.tf, landingzones/landingzone_networking/modules/firewall_rules/variables.tf, landingzones/landingzone_networking/variables.tf, landingzones/landingzone_networking/virtual_hub/arm_template_vhub_firewall.json, landingzones/landingzone_networking/virtual_hub/azure_firewall.tf, landingzones/landingzone_networking/virtual_hub/express_route_gateway.tf, landingzones/landingzone_networking/virtual_hub/main.tf, landingzones/landingzone_networking/virtual_hub/output.tf, landingzones/landingzone_networking/virtual_hub/point_to_site_gateway.tf, landingzones/landingzone_networking/virtual_hub/site_to_site_gateway.tf, landingzones/landingzone_networking/virtual_hub/variables.tf, landingzones/landingzone_networking/virtual_hub/virtual_hub.tf, landingzones/landingzone_networking/virtual_hubs.tf, landingzones/landingzone_networking/virtual_wan.tf
Refactoring to include all networking features into one networking landingzones.
=> Vnext13 networking refactoring

landingzones/landingzone_networking/examples/201-hub-spoke-vnets-firewall/configuration.tfvars, landingzones/landingzone_networking/modules/firewall_rules/application_rule_collection.tf, landingzones/landingzone_networking/modules/firewall_rules/network_rule_collection.tf, landingzones/landingzone_networking/route_table_association.tf
```
route_tables = {
from_spoke_to_hub = {
name = "spoke_aks_sg_to_hub_sg"
resource_group_key = "vnet_sg"
vnet_keys = {
"spoke_aks_sg" = {
subnet_keys = ["aks_nodepool_system","aks_nodepool_user1"]
}
}
route_entries = {
re1 = {
name                   = "defaultroute"
prefix                 = "0.0.0.0/0"
next_hop_type          = "VirtualAppliance"
azfw = {
VirtualAppliance_key   = "southeastasia"
ipconfig_index = 0
}
}
}
}
}
```
=> Add vnet_keys & subnet_keys to route_tables

landingzones/caf_launchpad/add-ons/azure_devops/solution.tf, landingzones/caf_launchpad/add-ons/azure_devops/variables.tf
add keyvault_access_policies_azuread_apps to Azure devops addon LZ
=> implement changes on kv access policies for kv

landingzones/caf_foundations/locals.remote_tfstates.tf, landingzones/caf_foundations/main.tf, landingzones/caf_launchpad/add-ons/azure_devops/main.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/main.tf, landingzones/caf_launchpad/landingzone.tf, landingzones/caf_launchpad/main.tf, landingzones/caf_networking/landingzone.tf, landingzones/caf_networking/locals.remote_tfstates.tf, landingzones/caf_networking/main.tf, landingzones/caf_networking/variables.tf, landingzones/caf_shared_services/landingzone.tf, landingzones/caf_shared_services/locals.remote_tfstates.tf, landingzones/caf_shared_services/main.tf
---
Add the capability to "inherit" tags from all landing zones inside a deployment from the launchpad tags.
Enabled by default in this release.
=> Update azurerm and update tag_inheritance from launchpad

documentation/code_architecture/hierarchy.md
---
Fix link in the documentation
- [] YES
=> Update hierarchy.md: Fix not working link

landingzones/caf_launchpad/add-ons/azure_devops/locals.remote_tfstates.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/locals.current_tfstates.tf
=> update tag inheritance

landingzones/caf_launchpad/add-ons/azure_devops/locals.remote_tfstates.tf
=> fix inherit tags in devops

landingzones/caf_launchpad/scenario/200/iam_azuread.tfvars, landingzones/caf_networking/scenario/105-hub-and-spoke/configuration.tfvars
=> Fix azuread roles

landingzones/caf_foundations/locals.remote_tfstates.tf, landingzones/caf_launchpad/add-ons/azure_devops/locals.remote_tfstates.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/locals.current_tfstates.tf, landingzones/caf_networking/locals.remote_tfstates.tf, landingzones/caf_shared_services/locals.remote_tfstates.tf, landingzones/caf_solutions/add-ons/aks_applications/locals.remote_tfstates.tf, landingzones/caf_solutions/add-ons/databricks/locals.remote_tfstates.tf, landingzones/caf_solutions/locals.remote_tfstates.tf
=> local tags will take precedence compare to inherited tags

landingzones/caf_foundations/landingzone.tf, landingzones/caf_foundations/locals.remote_tfstates.tf, landingzones/caf_foundations/output.tf, landingzones/caf_foundations/variables.tf
=> added Active Directory related resources to foundations part of security foundation

.gitignore, landingzones/caf_solutions/landingzone.tf
Depends on https://github.com/aztfmod/terraform-azurerm-caf/pull/277
---
=> Add support for keyvault_certificates

landingzones/caf_eslz/landingzone.tf, landingzones/caf_eslz/main.tf, landingzones/caf_foundations/dynamic_secrets.tf, landingzones/caf_foundations/landingzone.tf, landingzones/caf_foundations/main.tf, landingzones/caf_launchpad/add-ons/azure_devops/main.tf, landingzones/caf_launchpad/add-ons/azure_devops/solution.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/dynamic_secrets.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/main.tf, landingzones/caf_launchpad/add-ons/azure_devops_agent/solution.tf, landingzones/caf_launchpad/dynamic_secrets.tf, landingzones/caf_launchpad/landingzone.tf, landingzones/caf_launchpad/main.tf, landingzones/caf_networking/landingzone.tf, landingzones/caf_networking/main.tf, landingzones/caf_shared_services/landingzone.tf, landingzones/caf_shared_services/main.tf, landingzones/caf_shared_services/vm_extensions.tf, landingzones/caf_solutions/add-ons/databricks/main.tf, landingzones/caf_solutions/dynamic_secrets.tf, landingzones/caf_solutions/landingzone.tf, landingzones/caf_solutions/main.tf
=> update caf to version 5.2

documentation/README.md
Enterprise was misspelled. Couldn't let it escape a PR.
---
=> Spelling Error Quick Fix

documentation/code_architecture/intro_architecture.md
=> Fixed broken link to landing zone repository

landingzones/caf_solutions/add-ons/databricks/main.tf, landingzones/caf_solutions/modules/databricks/cluster.tf, landingzones/caf_solutions/modules/databricks/output.tf
NA. 
---
Update Databricks terraform with newer version to support diverse cluster configurations options 
Updated starter template to reflect the changes required
=> update databricks module and add additional options

caf_solution/add-ons/caf_eslz/custom_landing_zones.tf, caf_solution/add-ons/caf_eslz/variables.tf
=> Implement Subscription feedback to ESLZ

caf_solution/add-ons/azure_devops_agent/output.tf
=> Missing output for DevOps Agent Addon

caf_solution/local.remote.tf, caf_solution/local.security.tf, caf_solution/variables.security.tf
---
Added light house variables
=> added lighthouse variables

caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf, caf_solution/local.compute.tf, caf_solution/variables.compute.tf
=> Update for WVD and ADO Agents add-on interim refactoring

documentation/code_architecture/intro_architecture.md
The documentation was a little repetitive and the links were linking to obsolete launchpad blueprint documentation.
---
N/A - Documentation update only.
=> Tidying up the documentation for launchpads

.devcontainer/docker-compose.yml, .github/workflows/landingzones-tf13.yml, .github/workflows/landingzones-tf14.yml, .github/workflows/landingzones-tf15.yml, caf_solution/vm_extensions.tf
=> May rover update

caf_solution/add-ons/aks_applications/locals.remote_tfstates.tf, caf_solution/add-ons/databricks/locals.remote_tfstates.tf
---
- [ NA] I have updated the documentation accordingly.
- [ NA] I have added tests to cover my changes.
- [ Pending] All new and existing tests passed.
- [ x] My code follows the code style of this project.
- [ x] I ran lint checks locally prior to submission.
- [ x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
Updat global_settings key to match other locals.remote_tfstates.
- [ x] NO
=> Global settings fix

caf_launchpad/landingzone.tf, caf_launchpad/variables.tf, caf_solution/landingzone.tf, caf_solution/variables.tf
=> Add support for azuread map in launchpad and solution

caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf, caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
=> Fix ESLZ access control

caf_solution/landingzone.tf, caf_solution/local.remote.tf
=> Add vhub route tables as a remote object

caf_solution/landingzone.tf, caf_solution/local.remote.tf
=> 2105.patch firewall policy

caf_launchpad/output.tf, caf_launchpad/variables.tf, caf_solution/local.remote.tf, caf_solution/locals.remote_tfstates.tf, caf_solution/output.tf, caf_solution/variables.tf
=> Add launchpad_identities for azuread groups and msi from launchpad to propagate

caf_solution/local.compute.tf, caf_solution/variables.compute.tf
=> Add vmss to landingzone

caf_solution/output.tf
Diagnostics for caf_solution not exported correctly
---
=> Fixing diagnostics output for caf_solution

caf_launchpad/readme.md
---
Update documentation for rover apply commands that deploy the launchpad. Remove `/landingzones` from path
1. Clone the repository
2. Change directory to the root and run `rover login`
3. Try the different rover apply commands in `caf_launchpad/readme.md`
=> docs: update rover command file path

caf_solution/landingzone.tf, caf_solution/local.networking.tf, caf_solution/local.remote.tf, caf_solution/variables.networking.tf
---
Adds support for `vpn_sites` and `vpn_gateway_connections` contained in https://github.com/aztfmod/terraform-azurerm-caf/pull/518
=> Add support for vpn_sites and vpn_gateway_connections

caf_solution/add-ons/hashicorp_vault_secrets/local.remote_tfstates.tf, caf_solution/add-ons/hashicorp_vault_secrets/vault.tf, caf_solution/landingzone.tf
=> bug fix for add-on remote states

caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf, caf_solution/add-ons/caf_eslz/custom_landing_zones.tf, caf_solution/add-ons/caf_eslz/enterprise_scale.tf, caf_solution/add-ons/caf_eslz/locals.remote_tfstates.tf, caf_solution/add-ons/caf_eslz/subscription_id_overrides.tf, caf_solution/add-ons/caf_eslz/variables.tf
=> Add support for subscription_id_overrides_by_keys

caf_solution/local.remote.tf
=> Add remote

caf_solution/add-ons/aks_secure_baseline_v2/variables.tf
=> Update tag type in baseline v2 addon

caf_solution/add-ons/aks_secure_baseline_v2/output.tf
=> Update output.tf for aks_secure_baseline_v2

caf_solution/local.networking.tf, caf_solution/local.remote.tf, caf_solution/variables.networking.tf
=> Add nat_gateway module

caf_solution/add-ons/hashicorp_vault_secrets/scenario/101-simple-hashicorp-vault-secret-backend-role/azuread_applications.tfvars, caf_solution/add-ons/hashicorp_vault_secrets/scenario/101-simple-hashicorp-vault-secret-backend-role/configuration.tfvars, caf_solution/add-ons/hashicorp_vault_secrets/secret/scripts/set_vault_access.sh, caf_solution/add-ons/hashicorp_vault_secrets/secret/variables.tf, caf_solution/add-ons/hashicorp_vault_secrets/secret/vault_secret.tf, caf_solution/add-ons/hashicorp_vault_secrets/secret_backend_role/scripts/set_backend_secret_config.sh, caf_solution/add-ons/hashicorp_vault_secrets/secret_backend_role/variables.tf, caf_solution/add-ons/hashicorp_vault_secrets/secret_backend_role/vault_azure_secret_backend_role.tf, caf_solution/add-ons/hashicorp_vault_secrets/variables.tf, caf_solution/add-ons/hashicorp_vault_secrets/vault.tf, caf_solution/add-ons/hashicorp_vault_secrets/vault_azure_secret_backend_role.tf
=> Add support for Hashicorp vault secret backend role

caf_solution/local.remote.tf
=> AAD App remote object

caf_solution/local.compute.tf, caf_solution/local.remote.tf, caf_solution/variables.compute.tf, caf_solution/variables.tf
=> Adding vmware_clusters and vmware_private_cloud variables

caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
=> fix baseline network scope role assignment

caf_launchpad/readme.md, caf_solution/readme.md
=> fix a couple of broken links

caf_solution/add-ons/caf_eslz/locals.remote_tfstates.tf
---
In order to support more remote key referencing in eslz especially on azure policy parameter, loading a wider range of tfstate will be easier.
=> Support more resource type state in eslz

.github/workflows/landingzones-tf100.yml, caf_solution/vmss_extensions.tf
Adds support for virtual machine scale set custom script and domain join extensions.
Code is inspired from `vm_extensions.tf`.
Related to [PR 807](https://github.com/aztfmod/terraform-azurerm-caf/pull/807) from [terraform-azurerm-caf](https://github.com/aztfmod/terraform-azurerm-caf).
=> Add support for vmss custom script and domain join extensions

caf_solution/local.remote.tf
=> add remote support for ssl cert

caf_solution/add-ons/aks_applications/app/module.tf
Allows users to specify a chart version when using this module.
---
=> Add 'version' arg to aks_applications

caf_solution/local.networking.tf, caf_solution/variables.networking.tf
- Add variables to support cdn profile creation. 
- Needs to be merged along with Add support for cdn aztfmod/terraform-azurerm-caf#726.
- Tested and added a sample configuration tfvars to Add support for cdn aztfmod/terraform-azurerm-caf#726.
=> Add support for CDN

templates/platform/level0/launchpad/ansible.yaml
=> Aci network

templates/enterprise-scale/contoso/platform/single_subscription/launchpad.yaml, templates/resources/subscriptions.tfvars.j2
=> Fix missing asvm permissions in template in single sub

templates/resources/subscriptions.tfvars.j2
=> Patch asvm jinja subscription template

caf_solution/local.remote.tf
---
- Get the domain_name_registrations state into the local remote
- Needs to be merged along with the changes in this repository [terraform-azurerm-caf](https://github.com/aztfmod/terraform-azurerm-caf/pull/890)
- Tested and added a sample configuration in this repository [terraform-azurerm-caf](https://github.com/aztfmod/terraform-azurerm-caf/pull/890)
=> Add domain_name_registrations to local.remote.tf

documentation/getting_started/getting_started.md
=> Fix typo in Rancher Desktop name

caf_launchpad/documentation/variables.md, caf_launchpad/scenario/100/configuration.tfvars, caf_launchpad/scenario/200/configuration.tfvars, caf_launchpad/scenario/200/diagnostics_destinations.tfvars, caf_launchpad/variables.tf, caf_solution/scenario/networking/105-hub-and-spoke/configuration.tfvars, templates/ansible/load_deployments_alz.yaml, templates/ansible/walk-through-single.yaml, templates/platform/level0/launchpad/readme.md, templates/platform/single_subscription.yaml, templates/platform/template_topology.yaml
This PR fix an initial deployment issue with the Enterprise Scale library not pushed on the definition folder.
---
This PR fix an initial deployment issue with the Enterprise Scale library not pushed on the definition folder.
=> Deploy template library on initial setup with ignite

caf_solution/local.remote.tf, caf_solution/local.security.tf, caf_solution/variables.security.tf
=> Added sentinel

caf_solution/add-ons/aks_secure_baseline_v2/flux/flux.tf
=> Fix Flux for public repo

caf_solution/landingzone.tf, caf_solution/local.networking.tf, caf_solution/variables.networking.tf
=> Add variables for new LB module

caf_solution/local.remote.tf
=> Add remote support for postgresql_flexible_servers

caf_solution/local.compute.tf, caf_solution/variables.compute.tf
=> Added Ansible Module for Linux support

caf_solution/local.networking.tf, caf_solution/variables.networking.tf
=> Add support vhub route table routes

caf_solution/local.compute.tf, caf_solution/variables.compute.tf
---
Adding support for Azure Batch, see https://github.com/aztfmod/terraform-azurerm-caf/pull/1093
Ensure you're using a version of https://github.com/aztfmod/terraform-azurerm-caf that contains the batch modules, see https://github.com/aztfmod/terraform-azurerm-caf/pull/1093.
=> Add Azure Batch Support

templates/resources/data_factory_integration_runtime_self_hosted.tfvars.j2
---
Adds j2 resource template for the Data Factory Self-Hosted Integration Runtime resource type
- [ X ] NO
data_factory_integration_runtime_self_hosted:
dfirsh1:
name: adfsharedshir
resource_group:
key: integration
data_factory:
key: df1
=> Adds data factory self-hosted integration runtime j2 resource template

templates/resources/shared_image_galleries.tfvars.j2
---
- [X ] My code follows the code style of this project.
- [X ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
Adds resource template for Azure Shared Image Galleries
- [ X ] NO
shared_image_galleries:
gallery1:
name: img-gallery
resource_group_key: consumption
=> Adds shared_image_galleries resource template

caf_solution/local.networking.tf, caf_solution/variables.networking.tf
---
aztfmod/examples/networking/virtual_network/103-vnet-peering-v1
=> Add vnet_peerings_v1 - Better support vnet peerings between subscriptions

templates/resources/application_security_groups.tfvars.j2
---
Adds support for the application_security_groups resource to the resource templates
- [ X ] NO
=> Adds application_security_groups to resource templates

templates/resources/load_balancers.tfvars.j2
---
- [X ] My code follows the code style of this project.
- [X ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
Adds load_balancers to the available resource templates
- [X ] NO
load_balancers:
lb-vmss:
name: lb-vmss
sku: basic
resource_group_key: integration
backend_address_pool_name: vmss1
frontend_ip_configurations:
config1:
name: config1
public_ip_address_key: lb_pip1
probes:
probe1:
resource_group_key: integration
load_balancer_key: lb-vmss
probe_name: rdp
port: 3389
lb_rules:
rule1:
resource_group_key: integration
load_balancer_key: lb-vmss
lb_rule_name: rule1
protocol: tcp
probe_id_key: probe1
frontend_port: 3389
backend_port: 3389
frontend_ip_configuration_name: config1
=> Adds load_balancer resource template

caf_launchpad/landingzone.tf, caf_launchpad/local.custom_variables.tf, caf_launchpad/main.tf, caf_launchpad/variables.tf, templates/platform/level1/alz/ansible.yaml, templates/platform/level1/alz/lib/v1.1.3/archetype_config_overrides.tfvars.j2, templates/platform/level1/alz/lib/v1.1.3/custom_landing_zones.tfvars.j2, templates/platform/level1/alz/subscription_id_overrides.tfvars.j2
=> Add support for vhub connection to caf_launchpad

templates/platform/level1/alz/ansible.yaml, templates/platform/level1/alz/lib/v1.1.3/archetype_config_overrides.tfvars.j2, templates/platform/level1/alz/lib/v1.1.3/custom_landing_zones.tfvars.j2, templates/platform/level1/alz/subscription_id_overrides.tfvars.j2
=> Fix access control

caf_solution/local.shared_services.tf, caf_solution/variables.shared_services.tf
---
Add packer_build variable to use the packer_build module added to terraform-azurerm-caf
=> Add support for packer_build module

caf_solution/local.remote.tf
---
Fixes a bug where this [line](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/compute/virtual_machine/vm_windows.tf#L107) of code wouldn't function.
=> Add missing local.remote.image_definitions

caf_solution/local.shared_services.tf, caf_solution/variables.shared_services.tf
[#392](https://github.com/Azure/caf-terraform-landingzones/issues/392)
---
Add landingzones support for https://github.com/aztfmod/terraform-azurerm-caf/pull/1225
=> Add support for for azurerm_log_analytics_linked_service to link automation account and log analytics workspace

caf_solution/landingzone.tf, caf_solution/local.data_protection.tf, caf_solution/variables.data_protection.tf
=> Add data_protection variable

caf_solution/main.tf
---
Upgraded the minimum required `hashicorp/random` provider to 3.3.2 (current latest version), as I experienced an error downloading 3.1.0 (seemed like no ARM support for the M1 Macbooks).
=> Update hashicorp/random provider to 3.3.2

caf_solution/scenario/foundations/gitops/networking.tfvars
Fixing CD problem with Bastion subnet
=> Fix bastion subnetting

caf_solution/add-ons/azure_devops_agent/scripts/devops_runtime_baremetal.sh
=> Fix for [bug] - Azure devops self-hosted agent set too much privilege on the agent folder #414

caf_solution/local.webapp.tf, caf_solution/variables.webapp.tf
---
added support for static web app to caf_solution, see [aztfmod/terraform-azurerm-caf#1240](https://github.com/aztfmod/terraform-azurerm-caf/issues/1240)
Tested against 5.6.1 which contains the `static_sites` module
=> Add support for static web app to caf_solution

caf_solution/local.remote.tf, caf_solution/local.shared_services.tf, caf_solution/variables.shared_services.tf
=> adding Automation Variables

caf_solution/add-ons/azure_devops_agent/extensions/devops_selfhosted_agent.tf, caf_solution/add-ons/azure_devops_agent/main.tf, caf_solution/add-ons/azure_devops_agent/variables.tf, caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf
=> Upload Blob to Storage account to be used as VM extension

caf_solution/local.remote.tf
Add dns_resolver to remote to reference them with lz_key from remote state
---
=> Add dns_resolver to remote to reference them with lz_key from remote state

caf_launchpad/variables.provider.tf, caf_solution/variables.provider.tf
---
This PR changes the default azurerm feature settings to disable the purge of soft-delete objects
=> Change default provider features' settings

caf_launchpad/main.tf
Remove level tag preventing upgrade from 2203.0
---
=> Remove level tag preventing upgrade from 2203.0

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf
=> Update for module 5.6.9

caf_solution/local.azuread.tf, caf_solution/variables.azuread.tf
Add to caf_solution:
- azuread_administrative_units
- azuread_administrative_unit_members
---
=> Add azuread_administrative_units and azuread_administrative_unit_members

caf_solution/add-ons/azure_devops_agent/dynamic_secrets.tf, caf_solution/add-ons/azure_devops_agent/locals.current_tfstates.tf, caf_solution/add-ons/azure_devops_agent/main.tf, caf_solution/add-ons/azure_devops_agent/solution.tf, caf_solution/landingzone.tf
This PR helps to resolve the storage account blob read issue when provisioning an azure DevOps agent using this [addon](https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution/add-ons/aks_azure_devops_agents)
=> Fixes storage account issues for reading script as blob in azure DevOps agent add-on 

caf_launchpad/landingzone.tf, caf_launchpad/variables.tf, caf_solution/local.azuread.tf, caf_solution/variables.azuread.tf
---
Added support for conditional access when [PR ](https://github.com/aztfmod/terraform-azurerm-caf/pull/1315) is accepted.
=> Added support for azurerm conditional access

caf_launchpad/locals.remote_tfstates.tf, caf_launchpad/main.tf, caf_solution/add-ons/terraform_cloud/terraform_cloud.tf, caf_solution/landingzone.tf, caf_solution/local.networking.tf, caf_solution/local.remote.tf, caf_solution/variables.networking.tf
=> Add support for SQLMI deployment in multiple tfstates + network_security_security_rules

caf_solution/add-ons/aad-pod-identity/main.tf, caf_solution/add-ons/aks-secure-baseline/main.tf, caf_solution/add-ons/aks_applications/main.tf, caf_solution/add-ons/aks_applications_v2/main.tf, caf_solution/add-ons/aks_azure_devops_agents/main.tf, caf_solution/add-ons/aks_gitlab_agents/main.tf, caf_solution/add-ons/aks_secure_baseline_v2/main.tf, caf_solution/add-ons/azure_devops/main.tf, caf_solution/add-ons/azure_devops_v1/main.tf, caf_solution/add-ons/cross_tenant_hub_connection/main.tf, caf_solution/add-ons/databricks_v1/main.tf, caf_solution/add-ons/hashicorp_vault_secrets/main.tf, caf_solution/add-ons/helm-charts/main.tf, caf_solution/add-ons/secrets-store-csi-driver-provider-azure/main.tf, caf_solution/add-ons/terraform_cloud/main.tf
=> Update minimum terraform version to 1.3.0

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_launchpad/main.tf, caf_launchpad/scenario/200/configuration.tfvars, caf_solution/add-ons/aks_applications_v2/app/module.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf, caf_solution/main.tf
=> Update module to version = "5.6.10"

caf_launchpad/landingzone.tf, caf_launchpad/variables.tf, caf_solution/landingzone.tf, caf_solution/variables.tf
---
Add support to reference existing resources https://github.com/aztfmod/terraform-azurerm-caf/pull/1705
=> Add data_sources to existing resources

caf_solution/local.storage.tf, caf_solution/variables.storage.tf
---
Add support to create storage_account_file_shares not as nested within a storage account
=> Add storage_account_file_shares

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .github/workflows/landingzones-tf100.yml, .vscode/settings.json, rover_on_ssh_host.yml
=> Dev environment and rover updates 

.devcontainer/docker-compose.yml, .github/workflows/landingzones-tf100.yml, README.md, caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_launchpad/scenario/200/diagnostics_definition.tfvars, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf, caf_solution/local.maps.tf, caf_solution/scenario/networking/200-single-region-hub/configuration.tfvars, caf_solution/scenario/networking/201-multi-region-hub/configuration.tfvars, caf_solution/scenario/networking/210-aks-private/configuration.tfvars, caf_solution/variables.maps.tf, rover_on_ssh_host.yml, templates/resources/diagnostics_definition.tfvars.j2
- Update for module
- Update for rover
- Update doc
- Update retention settings example to align with https://github.com/hashicorp/terraform-provider-azurerm/issues/23051
=> September 2023 Updates

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf
=> Update module 5.7.6

.devcontainer/docker-compose.yml, .github/workflows/landingzones-tf100.yml, caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf, rover_on_ssh_host.yml
=> Module 5.7.8

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf
---
- [ x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
- [x ] NO
Update to 5.7.9 to include fix for https://github.com/aztfmod/terraform-azurerm-caf/pull/1906
=> Update terraform-azurerm-caf to 5.7.9

caf_solution/add-ons/azure_devops/scenario/200-contoso_demo/azure_devops.tfvars
=> Fix devops example

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf
Update terraform-azurerm-caf to 5.7.10
---
- [ x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
- [ x] NO
=> update terraform-azurerm-caf to 5.7.10

caf_launchpad/dynamic_secrets.tf, caf_launchpad/landingzone.tf, caf_solution/dynamic_secrets.tf, caf_solution/landingzone.tf
Update aztfmod version to 5.7.11 for caf-terraform-landingzones
---
- [ x] NO
=> update aztfmod to 5.7.11
